FROM ubuntu:latest

RUN apt-get update && \
    apt-get install -y openjdk-17-jdk wget unzip bash && \
    rm -rf /var/lib/apt/lists/*

ARG GROOVY_VERSION=4.0.21

RUN wget https://groovy.jfrog.io/artifactory/dist-release-local/groovy-zips/apache-groovy-binary-${GROOVY_VERSION}.zip -O groovy.zip && \
    unzip groovy.zip -d /opt && \
    rm groovy.zip && \
    ln -s /opt/groovy-${GROOVY_VERSION} /opt/groovy

ENV GROOVY_HOME=/opt/groovy
ENV PATH=$PATH:$GROOVY_HOME/bin

WORKDIR /app

CMD ["bash"]

